// app/layout.jsx
import { Geist, Geist_Mono } from "next/font/google";
import NavbarMobile from "@/components/NavbarMobile";
import Providers from "@/app/Providers";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100 min-h-screen`}
      >
        <div className='flex justify-center min-h-screen bg-gray-100'>
          <div className='w-full max-w-[430px] min-h-screen bg-white flex flex-col shadow-xl'>
            {/* Wrap your app with Providers */}
            <Providers>
              <main className='flex-1 pb-16'>{children}</main>
              <NavbarMobile />
            </Providers>
          </div>
        </div>
      </body>
    </html>
  );
}
