# Name of your workflow
name: Deploy to Firebase Hosting

# Run this workflow on pushes to the 'main' branch
on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner
    steps:
      # 1. Check out the repository code
      - name: Checkout Repo
        uses: actions/checkout@v4

      # 2. Set up Node.js (if your project needs it)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Specify your Node.js version

      # 3. Install dependencies and build the project
      - name: Install and Build
        run: |
          npm ci
          npm run build # Change this to your project's build command (e.g., ng build, yarn build)

      # 4. Deploy to Firebase Hosting
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}"
          channelId: live
          projectId: bethelia
